# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ADD COLLECTION COMMA DELETE DOCUMENT EQUALS ID LPAREN NUM RPAREN SEMICOLON SET STR UPDATE'
    
_lr_action_items = {'COLLECTION':([0,],[2,]),'$end':([1,22,28,36,],[0,-1,-2,-3,]),'LPAREN':([2,5,9,13,17,],[3,6,10,14,18,]),'STR':([3,6,10,14,18,21,26,],[5,9,13,17,21,25,30,]),'RPAREN':([7,11,15,19,25,30,],[8,12,16,20,27,36,]),'DOCUMENT':([8,12,16,20,],[11,15,19,23,]),'SET':([8,12,16,20,],[11,15,19,23,]),'UPDATE':([8,12,16,20,],[11,15,19,23,]),'DELETE':([8,12,16,20,],[11,15,19,23,]),'ADD':([8,12,16,20,],[11,15,19,23,]),'COMMA':([24,31,],[26,34,]),'SEMICOLON':([26,34,37,],[28,35,36,]),'EQUALS':([27,],[29,]),'NUM':([29,],[31,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,],[1,]),'key_values':([18,],[24,]),'key_value':([18,24,],[26,31,]),'value':([29,],[31,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> COLLECTION LPAREN STR RPAREN DOCUMENT LPAREN STR RPAREN SET LPAREN key_values RPAREN SEMICOLON','statement',13,'p_statement_create_document','analizador.py',75),
  ('statement -> COLLECTION LPAREN STR RPAREN ADD LPAREN key_values RPAREN SEMICOLON','statement',11,'p_statement_add_document','analizador.py',79),
  ('statement -> COLLECTION LPAREN STR RPAREN DOCUMENT LPAREN STR RPAREN UPDATE LPAREN key_values RPAREN SEMICOLON','statement',13,'p_statement_update_document','analizador.py',83),
  ('statement -> COLLECTION LPAREN STR RPAREN DOCUMENT LPAREN STR RPAREN DELETE SEMICOLON','statement',10,'p_statement_delete_document','analizador.py',87),
  ('key_values -> key_values COMMA key_value','key_values',3,'p_key_values','analizador.py',91),
  ('key_values -> key_value','key_values',1,'p_key_values','analizador.py',92),
  ('key_value -> STR EQUALS value','key_value',3,'p_key_value','analizador.py',96),
  ('value -> NUM','value',1,'p_value','analizador.py',100),
  ('value -> STR','value',1,'p_value','analizador.py',101),
]
